# -*- coding: utf-8 -*-

# Old file please not to refer

"""SolarpanelEfficiency.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11qKVwATfRP9_Jd29nPax19keafG1MPEa
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('/content/Plant_1_Generation_Data.csv')
df

null_values = df.isnull().sum()
null_values

all_duplicates = df.duplicated()
print(all_duplicates)

print("Shape of dataset:", df.shape)
print("\nFirst 5 rows:\n", df.head())
print("\nColumn info:\n")
print(df.info())
