# -*- coding: utf-8 -*-
"""SolarpanelEfficiency.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11qKVwATfRP9_Jd29nPax19keafG1MPEa
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('/content/Plant_1_Generation_Data.csv')
df

null_values = df.isnull().sum()
null_values

all_duplicates = df.duplicated()
print(all_duplicates)

print("Shape of dataset:", df.shape)
print("\nFirst 5 rows:\n", df.head())
print("\nColumn info:\n")
print(df.info())

categorical_cols = df.select_dtypes(include=['object']).columns
print("Categorical columns:", categorical_cols)

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
for col in categorical_cols: df[col] = label_encoder.fit_transform(df[col])

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

features = ['DATE_TIME', 'PLANT_ID','SOURCE_KEY','DC_POWER','AC_POWER','DAILY_YIELD',]
target = 'TOTAL_YIELD'
X = df[features]
y = df[target]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train

X_test

y_train

y_test

model = RandomForestRegressor(random_state=42)
model.fit(X_train, y_train)

y_pred = model.predict(X_test)
print("MSE:", mean_squared_error(y_test, y_pred))
print("R² Score:", r2_score(y_test, y_pred))